FROM node:alpine as builder
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .

# We don't start React Development Server here, intead we compile react source file into a build folder to serve it out
RUN npm run build 

# Our nginx server that sit behinh a nginx proxy and serve out the react page on port 3000
FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf 
COPY --from=builder /app/build /usr/share/nginx/htm