sudo: required
services:
  - docker
# To run test, we need to use our Development Docker file, look into the ./client

# to get the build context
before_install:
  - docker build -t hquach729/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true hquach729/client-test npm test

# Build image for Production Deployment
after_success:
  - docker build -t hquach729/workflow-proxy -f ./client/Dockerfile.prod ./proxy
  - docker build -t hquach729/workflow-client -f ./client/Dockerfile.prod ./client
  # Log in to the docker CLI, send the password to the next command in in the pipe
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hquach729/workflow-proxy
  - docker push hquach729/workflow-client
