version: '3'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: always
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
